spring.application.name=projet11
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

############################################################
# OpenRouteService API configuration
###########################################################
openrouteservice.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjgxOWRmMzBlYjFiOTQ0OGZiNzY5YzY3NjI0OTNkMDA5IiwiaCI6Im11cm11cjY0In0=
openrouteservice.api.url=https://api.openrouteservice.org