name: Test CI

on: [push]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Vérifier que ça tourne
        run: echo "GitHub Actions fonctionne bien !"
      - name: Lister les fichiers du repo
        run: ls -la