name: CI
on:
  push:
    branches:
      - Develop
  pull_request:
    branches:
      - Develop

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Vérifier que ça tourne
      run: echo "GitHub Actions fonctionne bien !"
    - name: Lister les fichiers du repo
      run: ls -la